recipe: default.v1
assistant_id: 20250302-074659-stubborn-rottweiler
language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer
    min_ngram: 1
    max_ngram: 1
  - name: DIETClassifier
    epochs: 10 
    embedding_dimension: 16 
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 10 
    embedding_dimension: 16  

policies:
  - name: RulePolicy
  - name: MemoizationPolicy
    max_history: 2  
  - name: TEDPolicy
    max_history: 2 
    epochs: 10  
    embedding_dimension: 16 
